-- Schema nền cho account, auth_session và lịch sử consent sức khỏe của Sprint 2.
-- Chạy an toàn nhiều lần: bảng/kiểu đã có thì bỏ qua.

DO $$ BEGIN
  CREATE TYPE account_role AS ENUM ('member', 'admin');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE account_status AS ENUM ('active', 'locked', 'deleted');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS account (
  account_id          BIGSERIAL PRIMARY KEY,
  email               VARCHAR(255)   NOT NULL UNIQUE,
  password_hash       VARCHAR(255)   NOT NULL,
  role                account_role   NOT NULL DEFAULT 'member',
  status              account_status NOT NULL DEFAULT 'active',
  full_name           VARCHAR(120),
  avatar_url          VARCHAR(500),
  bio                 VARCHAR(500),
  failed_login_count  SMALLINT       NOT NULL DEFAULT 0,
  locked_until        TIMESTAMPTZ,
  last_login_at       TIMESTAMPTZ,
  created_at          TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ    NOT NULL DEFAULT NOW()
);

-- Tìm theo email không phân biệt hoa/thường
CREATE UNIQUE INDEX IF NOT EXISTS account_email_lower_uq ON account (LOWER(email));

CREATE TABLE IF NOT EXISTS auth_session (
  session_id   UUID          PRIMARY KEY,
  account_id   BIGINT        NOT NULL REFERENCES account (account_id),
  token_hash   VARCHAR(255)  NOT NULL UNIQUE,
  device_id    VARCHAR(128),
  ip_address   VARCHAR(45),
  user_agent   VARCHAR(255),
  expires_at   TIMESTAMPTZ   NOT NULL,
  revoked_at   TIMESTAMPTZ,
  created_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS auth_session_device_idx  ON auth_session (device_id);
CREATE INDEX IF NOT EXISTS auth_session_account_idx ON auth_session (account_id);

-- Phần bổ sung so với ERD v4.2: lưu bằng chứng đồng ý/thu hồi consent theo phiên bản.
-- Bản ghi này không cascade khi Profile/Allergy bị xóa để giữ lịch sử consent.
CREATE TABLE IF NOT EXISTS public.health_consent_event (
  event_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id     BIGINT NOT NULL REFERENCES public.account (account_id),
  action         VARCHAR(16) NOT NULL CHECK (action IN ('granted', 'withdrawn')),
  policy_version VARCHAR(32) NOT NULL,
  policy_text    TEXT NOT NULL,
  occurred_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS health_consent_event_account_idx
  ON public.health_consent_event (account_id, occurred_at DESC, event_id DESC);
