-- Schema nền cho account, auth_session và hồ sơ sức khỏe của Sprint 2.
-- Chạy an toàn nhiều lần: bảng/kiểu đã có thì bỏ qua.

DO $$ BEGIN
  CREATE TYPE account_role AS ENUM ('member', 'admin');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE account_status AS ENUM ('active', 'locked', 'deleted');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS account (
  account_id          BIGSERIAL PRIMARY KEY,
  email               VARCHAR(255)   NOT NULL UNIQUE,
  password_hash       VARCHAR(255)   NOT NULL,
  role                account_role   NOT NULL DEFAULT 'member',
  status              account_status NOT NULL DEFAULT 'active',
  full_name           VARCHAR(120),
  avatar_url          VARCHAR(500),
  bio                 VARCHAR(500),
  failed_login_count  SMALLINT       NOT NULL DEFAULT 0,
  locked_until        TIMESTAMPTZ,
  last_login_at       TIMESTAMPTZ,
  created_at          TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ    NOT NULL DEFAULT NOW()
);

-- Tìm theo email không phân biệt hoa/thường
CREATE UNIQUE INDEX IF NOT EXISTS account_email_lower_uq ON account (LOWER(email));

CREATE TABLE IF NOT EXISTS auth_session (
  session_id   UUID          PRIMARY KEY,
  account_id   BIGINT        NOT NULL REFERENCES account (account_id),
  token_hash   VARCHAR(255)  NOT NULL UNIQUE,
  device_id    VARCHAR(128),
  ip_address   VARCHAR(45),
  user_agent   VARCHAR(255),
  expires_at   TIMESTAMPTZ   NOT NULL,
  revoked_at   TIMESTAMPTZ,
  created_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS auth_session_device_idx  ON auth_session (device_id);
CREATE INDEX IF NOT EXISTS auth_session_account_idx ON auth_session (account_id);

-- Duy's code: Khai báo các kiểu hồ sơ cần thiết cho model sức khỏe của Sprint 2.
DO $$ BEGIN
  CREATE TYPE public.profile_gender_enum AS ENUM ('male', 'female', 'other');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.bmi_category_enum AS ENUM ('underweight', 'normal', 'overweight', 'obese');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.activity_level_enum AS ENUM ('sedentary', 'light', 'moderate', 'active');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.health_goal_enum AS ENUM ('lose_weight', 'gain_muscle', 'maintain');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Duy's code: Tạo hồ sơ sức khỏe một-một với account và chỉ số do server tính.
CREATE TABLE IF NOT EXISTS public.profile (
  profile_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id           BIGINT NOT NULL,
  gender               public.profile_gender_enum,
  date_of_birth        DATE,
  height_cm            NUMERIC(5, 2),
  weight_kg            NUMERIC(5, 2),
  bmi                  NUMERIC(4, 1),
  bmi_category         public.bmi_category_enum,
  activity_level       public.activity_level_enum,
  health_goal          public.health_goal_enum,
  tdee_kcal            INTEGER,
  target_calories_kcal INTEGER,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_profile_account FOREIGN KEY (account_id) REFERENCES public.account (account_id),
  CONSTRAINT profile_account_id_key UNIQUE (account_id)
);

-- Duy's code: Lưu danh sách dị ứng/kiêng riêng theo hồ sơ và giới hạn tên như API.
CREATE TABLE IF NOT EXISTS public.allergy (
  allergy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id BIGINT NOT NULL,
  name       VARCHAR(120) NOT NULL,
  CONSTRAINT fk_allergy_profile FOREIGN KEY (profile_id) REFERENCES public.profile (profile_id)
);
