-- ERD_SWP PostgreSQL Schema
-- Source: 30_09 schema with report_case and simplified banned_keyword
-- Target: PostgreSQL 13+
-- Notes:
--   * BIGINT PKs use GENERATED BY DEFAULT AS IDENTITY.
--   * auth_session.session_id uses gen_random_uuid().
--   * No hard-delete ON DELETE actions are added; PostgreSQL defaults to NO ACTION.
--   * Polymorphic references intentionally have no physical foreign keys.
--   * Business authorization/moderation rules are handled by the backend.
--   * account.status includes 'reported' per confirmed requirement.

BEGIN;

-- =========================================================
-- 1. ENUM TYPES
-- =========================================================

CREATE TYPE account_status_enum AS ENUM (
    'active',
    'locked',
    'reported',
    'deleted'
);

CREATE TYPE profile_gender_enum AS ENUM (
    'male',
    'female',
    'other'
);

CREATE TYPE bmi_category_enum AS ENUM (
    'underweight',
    'normal',
    'overweight',
    'obese'
);

CREATE TYPE activity_level_enum AS ENUM (
    'sedentary',
    'light',
    'moderate',
    'active'
);

CREATE TYPE health_goal_enum AS ENUM (
    'lose_weight',
    'gain_muscle',
    'maintain'
);

CREATE TYPE post_type_enum AS ENUM (
    'blog',
    'video'
);

CREATE TYPE post_status_enum AS ENUM (
    'pending',
    'public',
    'reported',
    'deleted'
);

CREATE TYPE comment_status_enum AS ENUM (
    'public',
    'hidden',
    'deleted'
);

CREATE TYPE dish_status_enum AS ENUM (
    'pending',
    'active',
    'rejected',
    'hidden'
);

CREATE TYPE report_target_type_enum AS ENUM (
    'post',
    'comment',
    'recipe',
    'account'
);

CREATE TYPE report_reason_code_enum AS ENUM (
    'spam',
    'wrong_topic',
    'not_vegan',
    'abusive',
    'other'
);

CREATE TYPE report_status_enum AS ENUM (
    'pending',
    'accepted',
    'rejected'
);

CREATE TYPE notification_type_enum AS ENUM (
    'post_approved',
    'post_rejected',
    'post_hidden',
    'post_removed',
    'dish_approved',
    'dish_rejected',
    'comment_removed',
    'report_result',
    'account_locked',
    'shop_pending_verification',
    'shop_verified',
    'shop_rejected'
);

CREATE TYPE notification_ref_type_enum AS ENUM (
    'post',
    'comment',
    'dish',
    'account',
    'shop',
    'report'
);

CREATE TYPE admin_log_target_type_enum AS ENUM (
    'post',
    'comment',
    'recipe',
    'dish',
    'ingredient',
    'account',
    'category',
    'shop',
    'shop_dish',
    'report',
    'banned_keyword'
);

CREATE TYPE daily_quota_subject_type_enum AS ENUM (
    'device',
    'account'
);

CREATE TYPE meal_plan_source_enum AS ENUM (
    'manual',
    'ai'
);

CREATE TYPE meal_plan_status_enum AS ENUM (
    'draft',
    'saved',
    'archived'
);

CREATE TYPE meal_slot_enum AS ENUM (
    'breakfast',
    'lunch',
    'dinner',
    'snack'
);

CREATE TYPE nutrition_group_enum AS ENUM (
    'protein',
    'carb',
    'vegetable',
    'fat',
    'fruit'
);

CREATE TYPE chat_sender_enum AS ENUM (
    'user',
    'bot',
    'system'
);

CREATE TYPE chat_message_status_enum AS ENUM (
    'ok',
    'filtered',
    'error'
);

CREATE TYPE shop_status_enum AS ENUM (
    'active',
    'inactive',
    'renovating'
);

CREATE TYPE shop_verification_status_enum AS ENUM (
    'pending',
    'verified',
    'rejected'
);

-- =========================================================
-- 2. CORE TABLES
-- =========================================================

CREATE TABLE role (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE account (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role_id BIGINT NOT NULL,
    status account_status_enum NOT NULL,
    full_name VARCHAR(120),
    avatar_url VARCHAR(500),
    bio VARCHAR(500),
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_account_role
        FOREIGN KEY (role_id) REFERENCES role(role_id)
);

CREATE TABLE auth_session (
    session_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    account_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    device_id VARCHAR(128),
    ip_address VARCHAR(45),
    user_agent VARCHAR(255),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_auth_session_account
        FOREIGN KEY (account_id) REFERENCES account(account_id)
);

CREATE INDEX idx_auth_session_device_id
    ON auth_session(device_id);

CREATE TABLE profile (
    profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL UNIQUE,
    gender profile_gender_enum,
    date_of_birth DATE,
    height_cm DECIMAL(5,2),
    weight_kg DECIMAL(5,2),
    bmi DECIMAL(4,1),
    bmi_category bmi_category_enum,
    activity_level activity_level_enum,
    health_goal health_goal_enum,
    tdee_kcal INT,
    target_calories_kcal INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_profile_account
        FOREIGN KEY (account_id) REFERENCES account(account_id)
);

CREATE TABLE allergy (
    allergy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,

    CONSTRAINT fk_allergy_profile
        FOREIGN KEY (profile_id) REFERENCES profile(profile_id)
);

-- =========================================================
-- 3. CONTENT
-- =========================================================

CREATE TABLE post (
    post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    post_type post_type_enum NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    thumbnail_url VARCHAR(500),
    youtube_url VARCHAR(500),
    status post_status_enum NOT NULL DEFAULT 'pending',
    moderation_note VARCHAR(255),
    moderated_by BIGINT,
    moderated_at TIMESTAMPTZ,
    view_count INT NOT NULL DEFAULT 0,
    vote_count INT NOT NULL DEFAULT 0,
    comment_count INT NOT NULL DEFAULT 0,
    published_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_post_account
        FOREIGN KEY (account_id) REFERENCES account(account_id),

    CONSTRAINT fk_post_moderated_by
        FOREIGN KEY (moderated_by) REFERENCES account(account_id)
);

CREATE TABLE category (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE post_category (
    post_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,

    PRIMARY KEY (post_id, category_id),

    CONSTRAINT fk_post_category_post
        FOREIGN KEY (post_id) REFERENCES post(post_id),

    CONSTRAINT fk_post_category_category
        FOREIGN KEY (category_id) REFERENCES category(category_id)
);

CREATE TABLE comment (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    status comment_status_enum NOT NULL DEFAULT 'public',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_comment_post
        FOREIGN KEY (post_id) REFERENCES post(post_id),

    CONSTRAINT fk_comment_author
        FOREIGN KEY (author_id) REFERENCES account(account_id)
);

CREATE TABLE post_vote (
    post_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (post_id, account_id),

    CONSTRAINT fk_post_vote_post
        FOREIGN KEY (post_id) REFERENCES post(post_id),

    CONSTRAINT fk_post_vote_account
        FOREIGN KEY (account_id) REFERENCES account(account_id)
);

-- =========================================================
-- 4. DISHES, RECIPES, INGREDIENTS
-- =========================================================

CREATE TABLE dish (
    dish_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(500),
    thumbnail_url VARCHAR(500),
    est_calories_kcal INT,
    status dish_status_enum NOT NULL DEFAULT 'pending',
    moderation_note VARCHAR(255),
    moderated_by BIGINT,
    moderated_at TIMESTAMPTZ,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_dish_moderated_by
        FOREIGN KEY (moderated_by) REFERENCES account(account_id),

    CONSTRAINT fk_dish_created_by
        FOREIGN KEY (created_by) REFERENCES account(account_id)
);

CREATE TABLE dish_category (
    dish_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,

    PRIMARY KEY (dish_id, category_id),

    CONSTRAINT fk_dish_category_dish
        FOREIGN KEY (dish_id) REFERENCES dish(dish_id),

    CONSTRAINT fk_dish_category_category
        FOREIGN KEY (category_id) REFERENCES category(category_id)
);

CREATE TABLE recipe (
    recipe_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dish_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    thumbnail_url VARCHAR(500),
    youtube_url VARCHAR(500),
    servings SMALLINT,
    prep_time_minutes SMALLINT,
    cook_time_minutes SMALLINT,
    calories_kcal INT,
    instructions TEXT NOT NULL,

    CONSTRAINT fk_recipe_dish
        FOREIGN KEY (dish_id) REFERENCES dish(dish_id),

    CONSTRAINT fk_recipe_author
        FOREIGN KEY (author_id) REFERENCES account(account_id)
);

CREATE TABLE ingredient (
    ingredient_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    is_animal_derived BOOLEAN NOT NULL DEFAULT false,
    is_ngu_vi_tan BOOLEAN NOT NULL DEFAULT false,
    is_common_allergen BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE recipe_ingredient (
    recipe_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,
    amount DECIMAL(8,2),
    unit VARCHAR(30),

    PRIMARY KEY (recipe_id, ingredient_id),

    CONSTRAINT fk_recipe_ingredient_recipe
        FOREIGN KEY (recipe_id) REFERENCES recipe(recipe_id),

    CONSTRAINT fk_recipe_ingredient_ingredient
        FOREIGN KEY (ingredient_id) REFERENCES ingredient(ingredient_id)
);

-- =========================================================
-- 5. MODERATION & OPERATIONS
-- =========================================================

CREATE TABLE report_case (
    case_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type report_target_type_enum NOT NULL,
    target_id BIGINT NOT NULL,
    status report_status_enum NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    handled_by BIGINT,
    handled_at TIMESTAMPTZ,
    resolution_note VARCHAR(255),

    CONSTRAINT fk_report_case_handled_by
        FOREIGN KEY (handled_by) REFERENCES account(account_id),

    CONSTRAINT uq_report_case_identity_target
        UNIQUE (case_id, target_type, target_id)

    -- target_type + target_id is polymorphic; no physical FK.
);

CREATE UNIQUE INDEX uq_report_case_pending_target
    ON report_case(target_type, target_id)
    WHERE status = 'pending';

CREATE TABLE report (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL,
    reporter_id BIGINT NOT NULL,
    target_type report_target_type_enum NOT NULL,
    target_id BIGINT NOT NULL,
    reason_code report_reason_code_enum NOT NULL,
    reason_text TEXT,
    status report_status_enum NOT NULL DEFAULT 'pending',
    handled_by BIGINT,
    handled_at TIMESTAMPTZ,
    resolution_note VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_report_reporter
        FOREIGN KEY (reporter_id) REFERENCES account(account_id),

    CONSTRAINT fk_report_case
        FOREIGN KEY (case_id) REFERENCES report_case(case_id),

    CONSTRAINT fk_report_case_target
        FOREIGN KEY (case_id, target_type, target_id)
        REFERENCES report_case(case_id, target_type, target_id),

    CONSTRAINT fk_report_handled_by
        FOREIGN KEY (handled_by) REFERENCES account(account_id),

    CONSTRAINT uq_report_case_reporter
        UNIQUE (case_id, reporter_id)

    -- target_type + target_id is intentionally polymorphic:
    -- post, comment, recipe, account. No physical FK by design.
);

CREATE INDEX idx_report_case_latest_report
    ON report(case_id, created_at DESC);

CREATE TABLE notification (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    type notification_type_enum NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT,
    ref_type notification_ref_type_enum,
    ref_id BIGINT,
    is_read BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_notification_account
        FOREIGN KEY (account_id) REFERENCES account(account_id)

    -- ref_type + ref_id is intentionally polymorphic:
    -- post, comment, dish, account, shop, report. No physical FK by design.
);

CREATE TABLE banned_keyword (
    keyword_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(100) NOT NULL UNIQUE,
    normalized_keyword VARCHAR(100) NOT NULL
);

CREATE INDEX idx_banned_keyword_normalized_keyword
    ON banned_keyword(normalized_keyword);

CREATE TABLE admin_log (
    admin_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT NOT NULL,
    action VARCHAR(50) NOT NULL,
    target_type admin_log_target_type_enum NOT NULL,
    target_id BIGINT,
    reason VARCHAR(255),
    before_value JSONB,
    after_value JSONB,
    ip_address VARCHAR(45),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_admin_log_admin
        FOREIGN KEY (admin_id) REFERENCES account(account_id)

    -- target_type + target_id is intentionally polymorphic.
    -- No physical FK by design.
);

CREATE TABLE daily_quota (
    subject_type daily_quota_subject_type_enum NOT NULL,
    subject_key VARCHAR(128) NOT NULL,
    quota_date DATE NOT NULL,
    posts_viewed SMALLINT NOT NULL DEFAULT 0,
    chat_turns SMALLINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (subject_type, subject_key, quota_date)

    -- subject_type + subject_key is intentionally polymorphic:
    -- account or device. No physical FK by design.
);

-- =========================================================
-- 6. AI
-- =========================================================

CREATE TABLE meal_plan (
    meal_plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    title VARCHAR(200),
    start_date DATE,
    days_count SMALLINT NOT NULL DEFAULT 7,
    meals_per_day SMALLINT NOT NULL DEFAULT 3,
    source meal_plan_source_enum NOT NULL DEFAULT 'ai',
    bmi_snapshot DECIMAL(4,1),
    target_calories_kcal INT,
    goal_snapshot health_goal_enum,
    allergy_snapshot JSONB,
    available_ingredients TEXT,
    status meal_plan_status_enum NOT NULL DEFAULT 'draft',
    ai_model VARCHAR(60),
    prompt_tokens INT,
    completion_tokens INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_meal_plan_account
        FOREIGN KEY (account_id) REFERENCES account(account_id)
);

CREATE TABLE meal_plan_item (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_plan_id BIGINT NOT NULL,
    day_no SMALLINT NOT NULL,
    meal_slot meal_slot_enum NOT NULL,
    dish_id BIGINT NOT NULL,
    dish_name VARCHAR(200) NOT NULL,
    description TEXT,
    calories_kcal INT,
    nutrition_group nutrition_group_enum,
    ingredients JSONB,
    is_swapped BOOLEAN NOT NULL DEFAULT false,
    original_dish_name VARCHAR(200),

    CONSTRAINT fk_meal_plan_item_meal_plan
        FOREIGN KEY (meal_plan_id) REFERENCES meal_plan(meal_plan_id),

    CONSTRAINT fk_meal_plan_item_dish
        FOREIGN KEY (dish_id) REFERENCES dish(dish_id)

    -- Per specification, DO NOT add:
    -- UNIQUE (meal_plan_id, day_no, meal_slot)
);

CREATE TABLE chat_session (
    chat_session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT,
    device_id VARCHAR(128),
    is_trial BOOLEAN NOT NULL DEFAULT false,
    title VARCHAR(200),
    message_count INT NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL,
    last_activity_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,

    CONSTRAINT fk_chat_session_account
        FOREIGN KEY (account_id) REFERENCES account(account_id)
);

CREATE INDEX idx_chat_session_device_id
    ON chat_session(device_id);

CREATE TABLE chat_message (
    chat_message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_session_id BIGINT NOT NULL,
    sender chat_sender_enum NOT NULL,
    content TEXT NOT NULL,
    status chat_message_status_enum NOT NULL DEFAULT 'ok',
    tokens_used INT,
    ai_model VARCHAR(60),
    ref_post_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_chat_message_chat_session
        FOREIGN KEY (chat_session_id) REFERENCES chat_session(chat_session_id),

    CONSTRAINT fk_chat_message_ref_post
        FOREIGN KEY (ref_post_id) REFERENCES post(post_id)
);

-- =========================================================
-- 7. SHOPS
-- =========================================================

CREATE TABLE shop (
    shop_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    address VARCHAR(300) NOT NULL,
    phone VARCHAR(20),
    open_time TIME,
    close_time TIME,
    open_days VARCHAR(20),
    status shop_status_enum NOT NULL DEFAULT 'active',
    owner_account_id BIGINT NOT NULL UNIQUE,
    verification_status shop_verification_status_enum NOT NULL DEFAULT 'pending',
    verification_note VARCHAR(255),
    verified_at TIMESTAMPTZ,
    verified_by BIGINT,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_shop_owner_account
        FOREIGN KEY (owner_account_id) REFERENCES account(account_id),

    CONSTRAINT fk_shop_verified_by
        FOREIGN KEY (verified_by) REFERENCES account(account_id),

    CONSTRAINT fk_shop_created_by
        FOREIGN KEY (created_by) REFERENCES account(account_id)
);

CREATE TABLE shop_dish (
    shop_dish_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL,
    dish_id BIGINT NOT NULL,
    dish_category VARCHAR(80),
    price DECIMAL(10,2),
    ingredient_note TEXT,
    is_available BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by BIGINT,
    updated_by BIGINT,

    CONSTRAINT fk_shop_dish_shop
        FOREIGN KEY (shop_id) REFERENCES shop(shop_id),

    CONSTRAINT fk_shop_dish_dish
        FOREIGN KEY (dish_id) REFERENCES dish(dish_id),

    CONSTRAINT fk_shop_dish_created_by
        FOREIGN KEY (created_by) REFERENCES account(account_id),

    CONSTRAINT fk_shop_dish_updated_by
        FOREIGN KEY (updated_by) REFERENCES account(account_id)
);

-- =========================================================
-- 8. GENERIC updated_at TRIGGER
-- =========================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_account_set_updated_at
BEFORE UPDATE ON account
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_profile_set_updated_at
BEFORE UPDATE ON profile
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_post_set_updated_at
BEFORE UPDATE ON post
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_comment_set_updated_at
BEFORE UPDATE ON comment
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_dish_set_updated_at
BEFORE UPDATE ON dish
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_daily_quota_set_updated_at
BEFORE UPDATE ON daily_quota
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_meal_plan_set_updated_at
BEFORE UPDATE ON meal_plan
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_shop_set_updated_at
BEFORE UPDATE ON shop
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_shop_dish_set_updated_at
BEFORE UPDATE ON shop_dish
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 9. meal_plan_item.day_no VALIDATION
-- PostgreSQL CHECK constraints cannot safely reference another table,
-- so this cross-table rule is implemented with triggers.
-- =========================================================

CREATE OR REPLACE FUNCTION validate_meal_plan_item_day_no()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_days_count SMALLINT;
BEGIN
    SELECT days_count
      INTO v_days_count
      FROM meal_plan
     WHERE meal_plan_id = NEW.meal_plan_id;

    IF v_days_count IS NULL THEN
        RAISE EXCEPTION
            'meal_plan % does not exist or has invalid days_count',
            NEW.meal_plan_id;
    END IF;

    IF NEW.day_no < 1 OR NEW.day_no > v_days_count THEN
        RAISE EXCEPTION
            'day_no % must be between 1 and days_count % for meal_plan_id %',
            NEW.day_no,
            v_days_count,
            NEW.meal_plan_id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_meal_plan_item_validate_day_no
BEFORE INSERT OR UPDATE OF meal_plan_id, day_no
ON meal_plan_item
FOR EACH ROW
EXECUTE FUNCTION validate_meal_plan_item_day_no();

CREATE OR REPLACE FUNCTION prevent_invalid_meal_plan_days_count()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_max_day SMALLINT;
BEGIN
    IF NEW.days_count IS DISTINCT FROM OLD.days_count THEN
        SELECT MAX(day_no)
          INTO v_max_day
          FROM meal_plan_item
         WHERE meal_plan_id = OLD.meal_plan_id;

        IF v_max_day IS NOT NULL AND NEW.days_count < v_max_day THEN
            RAISE EXCEPTION
                'days_count % cannot be lower than existing max day_no % for meal_plan_id %',
                NEW.days_count,
                v_max_day,
                OLD.meal_plan_id;
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_meal_plan_validate_days_count
BEFORE UPDATE OF days_count
ON meal_plan
FOR EACH ROW
EXECUTE FUNCTION prevent_invalid_meal_plan_days_count();

-- =========================================================
-- 10. REQUIRED SEED DATA
-- =========================================================

INSERT INTO role (name)
VALUES
    ('member'),
    ('admin');

COMMIT;
